name: py38_pytorch
channels:
  - pyg
  - pytorch
  - bioconda
  - conda-forge
  - https://conda.rosettacommons.org
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20230802.0=h6a678d5_2
  - absl-py=1.4.0=py38h06a4308_0
  - aiohttp=3.9.3=py38h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=4.0.3=py38h06a4308_0
  - attrs=23.1.0=py38h06a4308_0
  - biopython=1.78=py38h7f8727e_0
  - blas=1.0=mkl
  - blinker=1.6.2=py38h06a4308_0
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli-python=1.0.9=py38h6a678d5_7
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.12.31=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2024.8.30=py38h06a4308_0
  - cffi=1.16.0=py38h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py38h06a4308_0
  - contrafold=2.02=h9948957_4
  - cryptography=41.0.7=py38hdda0065_0
  - cudatoolkit=11.3.1=h9edb442_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - frozenlist=1.4.0=py38h5eee18b_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - google-auth=2.22.0=py38h06a4308_0
  - google-auth-oauthlib=0.5.2=py38h06a4308_0
  - grpc-cpp=1.48.2=he1ff14a_4
  - grpcio=1.48.2=py38he1ff14a_4
  - gsl=2.7.1=h6e86dc7_1
  - gtest=1.14.0=hdb19cb5_0
  - idna=3.4=py38h06a4308_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libdeflate=1.7=h7f98852_5
  - libffi=3.4.4=h6a678d5_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=h166bdaf_0
  - libnsl=2.0.0=h5eee18b_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.20.3=he621ea3_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.3.0=hf544144_1
  - libuv=1.43.0=h7f98852_0
  - libwebp-base=1.2.2=h7f98852_1
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.4.1=py38h06a4308_0
  - markupsafe=2.1.3=py38h5eee18b_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - mpfr=4.2.1=h9458935_0
  - multidict=6.0.4=py38h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - numexpr=2.8.4=py38he184ba9_0
  - numpy=1.24.3=py38h14f4228_0
  - numpy-base=1.24.3=py38h31eccc5_0
  - oauthlib=3.2.2=py38h06a4308_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.15=h5eee18b_0
  - packaging=23.1=py38h06a4308_0
  - pandas=2.0.3=py38h1128e8f_0
  - perl=5.32.1=0_h5eee18b_perl5
  - pip=23.2.1=py38h06a4308_0
  - platformdirs=3.10.0=py38h06a4308_0
  - pooch=1.7.0=py38h06a4308_0
  - protobuf=3.20.3=py38h6a678d5_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py38h06a4308_0
  - pyopenssl=23.2.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.0.9=py38_torch_1.10.0_cu113
  - pytz=2023.3.post1=py38h06a4308_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.10.1=py38h14f4228_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - tensorboard-data-server=0.7.0=py38h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py38h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - urllib3=1.26.18=py38h06a4308_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yarl=1.9.3=py38h5eee18b_0
  - zipp=3.17.0=py38h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - addict==2.4.0
      - alignment-c==1.0.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - attrdict==2.0.1
      - backcall==0.2.0
      - captum==0.7.0
      - cellpose==4.0.4
      - clarabel==0.9.0
      - colorama==0.4.6
      - comm==0.2.2
      - configargparse==1.7
      - configparser==7.1.0
      - conformer==0.3.2
      - contourpy==1.1.1
      - csvsort==1.6.1
      - cvxpy==1.5.2
      - cycler==0.12.1
      - dash==2.17.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - datasets==2.18.0
      - decorator==5.1.1
      - dill==0.3.8
      - easydict==1.13
      - ecos==2.0.14
      - einops==0.8.0
      - et-xmlfile==1.1.0
      - evaluate==0.4.1
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - fastremap==1.15.1
      - filelock==3.13.3
      - fill-voids==2.1.0
      - flask==3.0.3
      - flatbuffers==24.3.25
      - fonttools==4.46.0
      - fsspec==2024.2.0
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-pasta==0.2.0
      - grad-cam==1.5.4
      - gurobipy==11.0.3
      - h5py==3.11.0
      - huggingface-hub==0.26.3
      - icecream==2.1.3
      - ignite==1.1.0
      - igraph==0.11.4
      - imagecodecs==2023.3.16
      - importlib-resources==6.1.1
      - ipython==8.12.3
      - ipywidgets==8.1.3
      - itk==5.4.0
      - itk-core==5.4.0
      - itk-filtering==5.4.0
      - itk-io==5.4.0
      - itk-numerics==5.4.0
      - itk-registration==5.4.0
      - itk-segmentation==5.4.0
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.11
      - keras==2.13.1
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.41.1
      - matplotlib==3.7.4
      - matplotlib-inline==0.1.7
      - mne==1.6.1
      - mpmath==1.3.0
      - multiprocess==0.70.16
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - network==0.1
      - networkx==3.1
      - numba==0.58.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - osqp==0.6.7.post1
      - parso==0.8.4
      - pathlib==1.0.1
      - patsy==0.5.6
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.3.0
      - pkgutil-resolve-name==1.3.10
      - plotly==5.22.0
      - progressbar2==4.5.0
      - prompt-toolkit==3.0.45
      - psutil==5.9.8
      - ptflops==0.7.2.2
      - ptyprocess==0.7.0
      - pulp==2.9.0
      - pure-eval==0.2.2
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pybind11==2.11.1
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pynvml==11.5.3
      - pyparsing==3.1.1
      - pyquaternion==0.9.9
      - python-utils==3.8.2
      - pyyaml==6.0.1
      - qdldl==0.1.7.post4
      - rarfile==4.2
      - referencing==0.35.1
      - regex==2024.11.6
      - responses==0.18.0
      - retrying==1.3.4
      - rna==0.13.2
      - rna-fm==0.2.2
      - rna-tools==3.22.5
      - roifile==2023.5.12
      - rpds-py==0.18.1
      - safetensors==0.4.5
      - scikit-learn==0.24.0
      - scs==3.2.7
      - seaborn==0.13.2
      - segment-anything==1.0
      - setuptools==58.0.4
      - simpleitk==2.3.1
      - simplejson==3.19.3
      - smmap==5.0.1
      - stack-data==0.6.3
      - statsmodels==0.14.1
      - sympy==1.13.3
      - tenacity==8.3.0
      - tensorboard==2.13.0
      - termcolor==2.4.0
      - texttable==1.7.0
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - tokenizers==0.20.3
      - torch==2.4.1+cu118
      - torch-geometric==2.5.2
      - torch-lr-finder==0.2.1
      - torch-sparse==0.6.13
      - torchaudio==2.4.1+cu118
      - torchvision==0.19.1+cu118
      - tqdm==4.66.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==3.0.0
      - ttach==0.0.3
      - typing-extensions==4.12.2
      - umap==0.1.1
      - umap-learn==0.5.7
      - versioneer==0.29
      - viennarna==2.7.0
      - vtk==9.3.0
      - wcwidth==0.2.13
      - werkzeug==3.0.3
      - wget==3.2
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - xxhash==3.4.1
prefix: /home/Shihx/yes/envs/py38_pytorch
